services:
  tk4:
    #image: tk4-herc
    image: tk4-mvs
    container_name: tk4-mvs
    ports:
      - "3270:3270"
      - "8038:8038"
    stdin_open: true     # Optional: for interactive console
    tty: true            # Optional: for interactive terminal
    volumes:
      - ./tk4_data/dasd:/tk4-/dasd
      - ./tk4_data/log:/tk4-/log
      - ./tk4_data/prt:/tk4-/prt
      - ./tk4_data/pch:/tk4-/pch
      - ./tk4_data/rdr:/tk4-/rdr
      - ./tk4_data/local_scripts:/tk4-/local_scripts
      - ./tk4_data/local_conf:/tk4-/local_conf
      - ./tk4_data/jcl:/tk4-/jcl
      - ./tk4_data/conf:/tk4-/conf

