#!/bin/bash
#**********************************************************************
#*** Script:  mvs - IPL OS/VS2-MVS 3.8j (TK4- unattended operations) ***
#**********************************************************************

# Detect architecture
a=$(uname -m)
if [[ ${a:0:3} == 'arm' ]]; then
   hf=$(readelf -A /proc/self/exe | grep Tag_ABI_VFP_args)
   if [[ ${hf:2:3} == 'Tag' ]]; then arch='arm'; else arch='arm_softfloat'; fi
elif [[ $a == 'x86_64' ]]; then
   arch=64
else
   arch=32
fi

# Detect OS
system=$(uname -s | awk '{print tolower($0)}')
case $system in
linux)
   force_arch=
   export PATH=hercules/$system/$arch/bin:$PATH
   export LD_LIBRARY_PATH=hercules/$system/$arch/lib:hercules/$system/$arch/lib/hercules:$LD_LIBRARY_PATH
   ;;
darwin)
   if [[ $arch == '32' ]]; then force_arch='arch -arch i386'; else force_arch=; fi
   export PATH=hercules/$system/bin:$PATH
   export DYLD_LIBRARY_PATH=hercules/$system/lib:hercules/$system/lib/hercules:$DYLD_LIBRARY_PATH
   ;;
*)
   echo "System $system not supported."
   exit 1
   ;;
esac

# Read mode
MODE=$(head -1 unattended/mode 2>/dev/null)
[[ $MODE == 'CONSOLE' ]] && unset DAEMON || DAEMON="-d"

# Source optional config
[[ -f local_conf/tk4-.parm ]] && . local_conf/tk4-.parm
[[ ${arch:0:3} == 'arm' && -z $REP101A ]] && export REP101A=specific
[[ $REP101A == 'specific' && -z $CMD101A ]] && export CMD101A=02

# Ensure log path
mkdir -p log

# Set IPL script
export HERCULES_RC=scripts/ipl.rc

# Run Hercules
exec $force_arch hercules "$DAEMON" -f conf/tk4-.cnf >>log/3033.log 2>&1
